name: Java CI with Gradle

on:
  push:
    branches: [ "stable" ]
  pull_request:
    branches: [ "stable" ]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle with caching
        uses: gradle/actions/setup-gradle@v4

      - name: Make Gradle Wrapper executable
        run: chmod +x ./gradlew

      - name: Build and test with Gradle
        run: ./gradlew build --scan

  dependency-submission:
    name: Dependency Submission
    if: github.event_name == 'push' && github.ref == 'refs/heads/stable'
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Submit dependencies to GitHub
        uses: gradle/actions/dependency-submission@v4